version: "3.5"

services:
 nginx:
  image: nginx:1.13
  restart: always
  container_name: nginx
  ports:
   - "80:80"
   - "443:443"
  networks:
   blog:
  volumes:
   - type: volume
     source: config
     target: /etc/nginx
   - type: volume
     source: project
     target: /project

volumes:
 config:
 project:
  name: blog_project

networks:
 blog:
  driver: bridge
  name: blog
